export const LOCAL_DNS = 'http://192.168.1.54:9090';//verifier ipconfig avant d'exécuter
export const PROD_DNS = "https://api.leganda.chillo.fr";
export const IMAGES_URL = `${PROD_DNS}/assets`;
export const BACKOFFICE_URL = `${PROD_DNS}/api/v1`;
export const ADS_ENDPOINT = "ad";
export const FAVORITE_ENDPOINT = "favorite";
export const ACCOUNT_ENDPOINT = "account";
export const ADDRESS_ENDPOINT = "address";
export const CATEGORY_ENDPOINT="category";
