name: deploiement
on: [push]
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: clone du projet
        uses: actions/checkout@v2

      - name: JDK environnenment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: chemin du repertoire
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: restore les modules cachees
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Installation des dependences # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn install --immutable

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_SECRET }}

      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_SECRET }}" ]; then
                    echo "You must provide an EXPO_SECRET secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
                    exit 1
          fi
          

      - name: Publish deploiement
        run: eas update --auto
