name: deploiement
on: [push]
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: clone du projet
        uses: actions/checkout@v2

      - name: check
        run: ls -al

      - name: JDK environnenment
        uses: actions/setup-java@v1.4.3
        with:
        java-version: 1.8
        
