name: deploiement
on: [push]
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: clone du projet
        uses: actions/checkout@v2

      - name: check
        run: ls -al

      - name: JDK environnenment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: chemin du repertoire
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: restore les modules cachees
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-   

      - name: Installation des dependences # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

